# Generated by Django 5.1.3 on 2024-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
