# Generated by Django 5.1.3 on 2024-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_edge_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='relation_type',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
