# Generated by Django 5.1.3 on 2024-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_alter_edge_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='relation_type',
            field=models.CharField(choices=[('diplomatic', 'Diplomatique'), ('economic', 'Économique'), ('humanitarian', 'Humanitaire'), ('undefined', 'Non défini')], default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('from_node', 'to_node', 'relation_type')},
        ),
    ]
