# Generated by Django 5.1.3 on 2024-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_alter_edge_relation_type_alter_node_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
